// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsMIAwOteAWABN8UgTBH0zHVjNjHxQexk',
    appId: '1:593867694517:web:3b26ddcc9eb3c3d24b39fc',
    messagingSenderId: '593867694517',
    projectId: 'flutter-app-midterm-b00dd',
    authDomain: 'flutter-app-midterm-b00dd.firebaseapp.com',
    databaseURL: 'https://flutter-app-midterm-b00dd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-midterm-b00dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFNv8NRG0sOPRg6g7mwvlirdy-3YZcP3o',
    appId: '1:593867694517:android:3b471ec0f7b3a8fe4b39fc',
    messagingSenderId: '593867694517',
    projectId: 'flutter-app-midterm-b00dd',
    databaseURL: 'https://flutter-app-midterm-b00dd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-midterm-b00dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbYIVwmpGgJEroUBEUPtf4KVmiRuUCIUE',
    appId: '1:593867694517:ios:c3e82c9027a98b784b39fc',
    messagingSenderId: '593867694517',
    projectId: 'flutter-app-midterm-b00dd',
    databaseURL: 'https://flutter-app-midterm-b00dd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-midterm-b00dd.appspot.com',
    iosBundleId: 'com.example.flutterAppMidterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbYIVwmpGgJEroUBEUPtf4KVmiRuUCIUE',
    appId: '1:593867694517:ios:c3e82c9027a98b784b39fc',
    messagingSenderId: '593867694517',
    projectId: 'flutter-app-midterm-b00dd',
    databaseURL: 'https://flutter-app-midterm-b00dd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-midterm-b00dd.appspot.com',
    iosBundleId: 'com.example.flutterAppMidterm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsMIAwOteAWABN8UgTBH0zHVjNjHxQexk',
    appId: '1:593867694517:web:e38c4feafce15de04b39fc',
    messagingSenderId: '593867694517',
    projectId: 'flutter-app-midterm-b00dd',
    authDomain: 'flutter-app-midterm-b00dd.firebaseapp.com',
    databaseURL: 'https://flutter-app-midterm-b00dd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-midterm-b00dd.appspot.com',
  );

}